# Site settings

title: iSC Inc. Wiki Farm
description: The collaborate wiki farm of iSC Inc.

baseurl: "/farm"
url: "http://iscinc.github.io"
files_url: http://iscinc.github.io/assets/

email: github@inc.isc

google_analytics_id: UA-54991804-4

repository: https://github.com/iSCInc/farm

# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Plugins
whitelist: []
gems:      ["jekyll-sitemap", "jemoji", "jekyll-mentions"]

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
